"""
main.py
-------
FastAPI application entry point.

Run with:  uvicorn main:app --reload --port 8000
Docs at:   http://localhost:8000/docs   (auto-generated by FastAPI/Pydantic)
"""

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from dotenv import load_dotenv

from models.database import init_db
from routes.resume_routes import router as resume_router

load_dotenv()  # reads backend/.env if present

app = FastAPI(
    title="AI Resume Analyzer API",
    description="Upload a resume, get an ATS score, skill analysis, and AI-generated feedback.",
    version="1.0.0",
)

# Allow the Vite dev server (and any deployed frontend origin you add) to
# call this API from the browser.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # tighten this to your real frontend URL in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.on_event("startup")
def on_startup():
    init_db()


@app.exception_handler(Exception)
async def unhandled_exception_handler(request: Request, exc: Exception):
    """Catch-all so a bug never leaks a raw Python traceback to the client."""
    return JSONResponse(
        status_code=500,
        content={"detail": "An unexpected server error occurred. Please try again."},
    )


@app.get("/")
async def root():
    return {"status": "ok", "service": "AI Resume Analyzer API"}


@app.get("/health")
async def health():
    return {"status": "healthy"}


app.include_router(resume_router, prefix="/api", tags=["resume"])
